name: Backend CD

on:
  push:
    branches: [ "main" ]
    # See. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
    paths: [ "backend/**" ]

  workflow_dispatch:
    inputs:
      image:
        description: "the full docker image name + tag to be deployed"
        required: true
        default: ''

jobs:
  build-and-deploy-backend:
    if: inputs.image == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build backend docker image 
        working-directory: backend
        run: | 
          docker build -t ghcr.io/csimonmeunier/socra-group16/socarotte-backend:${{ github.sha }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker push ghcr.io/csimonmeunier/socra-group16/socarotte-backend:${{ github.sha }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker stop socarotte-backend 2> /dev/null && docker rm socarotte-backend 2> /dev/null
            docker run -d --network web \
              --name socarotte-backend \
              --label "traefik.http.routers.socarotte-backend.rule=Host(\`api.group16.socra-sigl.fr\`)" \
              --label "traefik.http.routers.socarotte-backend.tls=true" \
              --label "traefik.http.routers.socarotte-backend.tls.certresolver=myresolver" \
              --label "traefik.enable=true" \
              --label "traefik.docker.network=web" \
              ghcr.io/csimonmeunier/socra-group16/socarotte-backend:${{ github.sha }}

  deploy-backend-from-image:
    if: inputs.image != ''
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker stop socarotte-backend 2> /dev/null && docker rm socarotte-backend 2> /dev/null
            docker run -d --network web \
              --name socarotte-backend \
              --label "traefik.http.routers.socarotte-backend.rule=Host(\`api.group16.socra-sigl.fr\`)" \
              --label "traefik.http.routers.socarotte-backend.tls=true" \
              --label "traefik.http.routers.socarotte-backend.tls.certresolver=myresolver" \
              --label "traefik.enable=true" \
              --label "traefik.docker.network=web" \
              ${{ inputs.image }}