# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker image 
        run: |
          export CR_PAT=${{ secrets.DOCKER_PASSWORD }}}
          echo $CR_PAT | docker login ghcr.io -u ${{ github.DOCKER_USER }} --password-stdin
          docker build -t ghcr.io/csimonmeunier/socra-group16/socarotte-frontend:${{ github.sha }} .
